---
# [Autofix | INI Formatter]
#   autofix your INI format using "prettier-plugin-ini" package
#   to your changes files.
name: Autofix | INI Formatter

on:
  pull_request:
    branches: main
    paths: '**.ini'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  formatter:
    runs-on: ubuntu-latest
    if: github.actor != 'verlandz-bot'
    steps:
      - name: Install Node18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install prettier-plugin-ini
        run: npm install --prefix ../ prettier prettier-plugin-ini

      - name: Checkout pull-request branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_PAT }}

      - name: Execute Prettier
        id: execute
        run: |
          git fetch origin main
          errMsg=""

          files=$(git diff --name-status origin/main | grep '.ini$' | awk '$1 != "D" {print $NF}')
          for file in $files
          do
            echo "Formatting $file"
            if res=$(../node_modules/.bin/prettier --write $file 2>&1)
            then
              echo "OK"
            else
              echo -n "::error::"
              echo "$res" | tee res.out

              errMsg+="<li><b>$file</b></li>"
              errMsg+="<pre>"

              while read line;
              do
                errMsg+="<div>$line</div>"
              done < res.out

              errMsg+="</pre>"
            fi
          done

          echo "message=$errMsg" >> $GITHUB_OUTPUT
          if [ "$errMsg" != "" ]
          then
            exit 1
          fi

      - name: Report failure
        if: failure()
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.BOT_PAT }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            **[Failed]** INI Formatter failed :x:
            <details>
              <summary>Error Messages</summary>
              ${{ steps.execute.outputs.message }}
            </details>

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.event.pull_request.head.ref || github.head_ref || github.ref }}
          commit_user_name: 'verlandz-bot'
          commit_user_email: '111285852+verlandz-bot@users.noreply.github.com'
          commit_message: '[BOT] Autofix | INI Formatter'
