---
# [Autofix | YAML/YML Formatter]
#   autofix your YAML/YML file changes using "prettier".
name: Autofix | YAML/YML Formatter (Beta)

on:
  pull_request:
    branches:
      - main
      - beta
    paths:
      - '**.yaml'
      - '**.yml'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  formatter:
    runs-on: ubuntu-latest
    if: github.actor != 'verlandz-bot'
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install prettier
        run: npm install --save-dev --save-exact prettier

      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_PAT }}

      - name: Formatter
        id: formatter
        run: |
          git fetch origin ${{ github.base_ref }}

          prettier_path=.github/workflows/supports/.prettierrc
          npx prettier --find-config-path $prettier_path

          files=$(git diff --name-status origin/${{ github.base_ref }} | grep -E ".yaml$|.yml$" | awk '$1 != "D" {print $NF}')
          for file in $files
          do
            echo "Formatting $file"
            if res=$(npx prettier --config $prettier_path --write $file 2>&1)
            then
              echo "OK"
            else
              echo -n "::error:: $res"
              errMsg="$res"
              errMsg="${errMsg//'%'/'<br>'}"
              errMsg="${errMsg//$'\n'/'<br>'}"
              errMsg="${errMsg//$'\r'/'<br>'}"

              echo "err_msg=$errMsg" >> $GITHUB_OUTPUT
              exit 1
            fi
          done

      - name: Report failure
        if: failure()
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.BOT_PAT }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### YAML/YML Formatter :x:
            <details>
              <summary>Details</summary>
              <pre>${{ steps.formatter.outputs.err_msg }}</pre>
            </details>

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.head_ref }}
          commit_user_name: 'verlandz-bot'
          commit_user_email: 'verlandz-bot@users.noreply.github.com'
          commit_message: '[BOT] Autofix | YAML/YML Formatter'
