---
# [Autofix | Go Formatter]
#   autofix your GO format using "go fmt"
#   to your changes files.
name: Autofix | Go Formatter

on:
  pull_request:
    branches: main
    paths: '**.go'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  formatter:
    runs-on: ubuntu-latest
    if: github.actor != 'verlandz-bot'
    steps:
      - name: Install Go18
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x

      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_PAT }}

      - name: Execute go fmt
        id: execute
        run: |
          git fetch origin main

          files=$(git diff --name-status origin/main | grep '.go$' | awk '$1 != "D" {print $NF}')
          for file in $files
          do
            echo "Formatting $file"
            if res=$(go fmt $file 2>&1)
            then
              echo "OK"
            else
              echo -n "::error:: $res"
              errMsg="$res"
              errMsg="${errMsg//'%'/'<br>'}"
              errMsg="${errMsg//$'\n'/'<br>'}"
              errMsg="${errMsg//$'\r'/'<br>'}"

              echo "msg=$errMsg" >> $GITHUB_OUTPUT
              exit 1
            fi
          done

      - name: Report failure
        if: failure()
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.BOT_PAT }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### GO Formatter :x:
            <details>
              <summary>Details</summary>
              <pre>${{ steps.execute.outputs.msg }}</pre>
            </details>

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.event.pull_request.head.ref || github.head_ref || github.ref }}
          commit_user_name: 'verlandz-bot'
          commit_user_email: 'verlandz-bot@users.noreply.github.com'
          commit_message: '[BOT] Autofix | Go Formatter'
