---
# [Autofix | YAML/YML Formatter]
#   will autofix your YAML/YML format using 'yamlfmt'
#   to your changes files.
name: Autofix | YAML/YML Formatter

on:
  pull_request:
    branches: main
    paths:
      - '**.yaml'
      - '**.yml'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  formatter:
    runs-on: ubuntu-20.04
    if: github.actor != 'verlandz-bot'
    steps:
      - name: Install Node14
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install npm
        run: npm install --save-dev --save-exact prettier

      - name: Checkout pull-request branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_PAT }}

      - name: Execute yamlfmt
        run: |
          git fetch origin main
          files=$(git diff --name-status origin/main | grep -E '.yaml$|.yml$' | awk '{print $2}')
          prettier_path=.github/workflows/supports/.prettierrc
          prettier --find-config-path prettier_path
          for file in $files
          do
            npx prettier --config prettier_path --write $file
          done 

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.event.pull_request.head.ref || github.head_ref || github.ref }}
          commit_user_name: 'verlandz-bot'
          commit_user_email: '111285852+verlandz-bot@users.noreply.github.com'
          commit_message: '[BOT] Autofix | YAML/YML Formatter'
