---
# [Autofix | YAML/YML Formatter]
#   will autofix your YAML/YML format using "prettier"
#   to your changes files.
name: Autofix | YAML/YML Formatter

on:
  pull_request:
    branches: main
    paths:
      - '**.yaml'
      - '**.yml'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  formatter:
    runs-on: ubuntu-latest
    if: github.actor != 'verlandz-bot'
    steps:
      - name: Install Node18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install npm
        run: npm install --save-dev --save-exact prettier

      - name: Checkout pull-request branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_PAT }}

      - name: Execute prettier
        id: execute
        run: |
          git fetch origin main
          errMsg=""

          prettier_path=.github/workflows/supports/.prettierrc
          npx prettier --find-config-path $prettier_path

          files=$(git diff --name-status origin/main | grep -E ".yaml$|.yml$" | awk '{print $2}')
          for file in $files
          do
            echo "Formatting $file"
            if res=$(npx prettier --config $prettier_path --write $file 2>&1)
            then
              echo "OK"
            else
              echo "$res" | tee res.out

              errMsg+="<li><b>$file</b></li>"
              errMsg+="<pre><code>"

              while read line;  
              do
                errMsg+="<div>$line</div>"
              done < res.out

              errMsg+="</pre></code>"
            fi
          done

          echo "message=$errMsg" >> $GITHUB_OUTPUT
          if [ "$errMsg" != "" ]
          then
            exit 1
          fi

      - name: Report failure
        if: failure()
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.BOT_PAT }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            **[Failed]** YAML/YML Formatter failed :x:
            <details>
              <summary>Error Messages</summary>
              ${{ steps.execute.outputs.message }}
            </details>

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.event.pull_request.head.ref || github.head_ref || github.ref }}
          commit_user_name: 'verlandz-bot'
          commit_user_email: '111285852+verlandz-bot@users.noreply.github.com'
          commit_message: '[BOT] Autofix | YAML/YML Formatter'
