---
# [Autofix | INI Formatter]
#   autofix your INI format using "prettier-plugin-ini" package
#   to your changes files.
name: Autofix | INI Formatter

on:
  pull_request:
    branches: main
    paths: '**.ini'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  formatter:
    runs-on: ubuntu-latest
    if: github.actor != 'verlandz-bot'
    steps:
      - name: Install Node18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install prettier-plugin-ini
        run: npm install --prefix ../ prettier prettier-plugin-ini

      - name: Checkout pull-request branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_PAT }}

      - name: Execute Prettier
        id: execute
        run: |
          git fetch origin main

          files=$(git diff --name-status origin/main | grep '.ini$' | awk '$1 != "D" {print $NF}')
          for file in $files
          do
            echo "Formatting $file"
            if res=$(../node_modules/.bin/prettier --write $file 2>&1)
            then
              echo "OK"
            else
              echo -n "::error:: $res"
              errMsg="$res"
              errMsg="${errMsg//'%'/'<br>'}"
              errMsg="${errMsg//$'\n'/'<br>'}"
              errMsg="${errMsg//$'\r'/'<br>'}"

              echo "msg=$errMsg" >> $GITHUB_OUTPUT
              exit 1
            fi
          done

      - name: Report failure
        if: failure()
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.BOT_PAT }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### :x: INI Formatter
            <details>
              <summary>Details</summary>
              <pre>${{ steps.execute.outputs.msg }}</pre>
            </details>

      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.event.pull_request.head.ref || github.head_ref || github.ref }}
          commit_user_name: 'verlandz-bot'
          commit_user_email: 'verlandz-bot@users.noreply.github.com'
          commit_message: '[BOT] Autofix | INI Formatter'
