---
# [Code Coverage | Go]
#   test your Go coverage files using "go test" to
#   - "main" branch
#   - "your" branch
#   - merged("main"+"your") branch
name: Code Coverage | Go

on:
  pull_request:
    branches: main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  ignore-bot:
    runs-on: ubuntu-latest
    if: github.actor != 'verlandz-bot'
    steps:
      - run: ''

  test-coverage-main-branch:
    runs-on: ubuntu-latest
    needs: [ignore-bot]
    outputs:
      threshold: ${{ steps.coverage-output.outputs.threshold }}
      percentage: ${{ steps.coverage-output.outputs.percentage }}
      message: ${{ steps.coverage-output.outputs.message }}
    steps:
      - name: Install Go18
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x

      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.BOT_PAT }}

      - name: Test coverage main branch
        run: make test

      - name: Create coverage output
        id: coverage-output
        if: always()
        run: |
          echo "$(git log -1)"
          echo "go-coverage-percentage: $(cat go-coverage-percentage.out)%"
          echo "go-coverage-message: $(cat go-coverage-message.out)"

          covMsg=$(cat go-coverage-message.out)
          covMsg="${covMsg//'%'/'<br>'}"
          covMsg="${covMsg//$'\n'/'<br>'}"
          covMsg="${covMsg//$'\r'/'<br>'}"

          echo "threshold=$(cat go-coverage-threshold.out)" >> $GITHUB_OUTPUT
          echo "percentage=$(cat go-coverage-percentage.out)" >> $GITHUB_OUTPUT
          echo "message=$covMsg" >> $GITHUB_OUTPUT

  test-coverage-your-branch:
    runs-on: ubuntu-latest
    needs: [ignore-bot]
    outputs:
      threshold: ${{ steps.coverage-output.outputs.threshold }}
      percentage: ${{ steps.coverage-output.outputs.percentage }}
      message: ${{ steps.coverage-output.outputs.message }}
    steps:
      - name: Install Go18
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x

      - name: Checkout your branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref || github.head_ref || github.ref }}
          token: ${{ secrets.BOT_PAT }}

      - name: Test coverage your branch
        run: make test

      - name: Create coverage output
        id: coverage-output
        if: always()
        run: |
          echo "$(git log -1)"
          echo "go-coverage-percentage: $(cat go-coverage-percentage.out)%"
          echo "go-coverage-message: $(cat go-coverage-message.out)"

          covMsg=$(cat go-coverage-message.out)
          covMsg="${covMsg//'%'/'<br>'}"
          covMsg="${covMsg//$'\n'/'<br>'}"
          covMsg="${covMsg//$'\r'/'<br>'}"

          echo "threshold=$(cat go-coverage-threshold.out)" >> $GITHUB_OUTPUT
          echo "percentage=$(cat go-coverage-percentage.out)" >> $GITHUB_OUTPUT
          echo "message=$covMsg" >> $GITHUB_OUTPUT

  test-coverage-merged-branch:
    runs-on: ubuntu-latest
    needs: [ignore-bot]
    outputs:
      threshold: ${{ steps.coverage-output.outputs.threshold }}
      percentage: ${{ steps.coverage-output.outputs.percentage }}
      message: ${{ steps.coverage-output.outputs.message }}
    steps:
      - name: Install Go18
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x

      - name: Checkout merged branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_PAT }}

      - name: Test coverage merged branch
        run: make test

      - name: Create coverage output
        id: coverage-output
        if: always()
        run: |
          echo "$(git log -1)"
          echo "go-coverage-percentage: $(cat go-coverage-percentage.out)%"
          echo "go-coverage-message: $(cat go-coverage-message.out)"

          covMsg=$(cat go-coverage-message.out)
          covMsg="${covMsg//'%'/'<br>'}"
          covMsg="${covMsg//$'\n'/'<br>'}"
          covMsg="${covMsg//$'\r'/'<br>'}"

          echo "threshold=$(cat go-coverage-threshold.out)" >> $GITHUB_OUTPUT
          echo "percentage=$(cat go-coverage-percentage.out)" >> $GITHUB_OUTPUT
          echo "message=$covMsg" >> $GITHUB_OUTPUT

  comparison:
    if: always() && github.actor != 'verlandz-bot'
    runs-on: ubuntu-latest
    needs: [test-coverage-main-branch, test-coverage-your-branch, test-coverage-merged-branch]
    env:
      THRES_MAIN_BRANCH: ${{ needs.test-coverage-main-branch.outputs.threshold }}
      THRES_YOUR_BRANCH: ${{ needs.test-coverage-your-branch.outputs.threshold }}
      THRES_MERGED_BRANCH: ${{ needs.test-coverage-merged-branch.outputs.threshold }}
      COV_MAIN_BRANCH: ${{ needs.test-coverage-main-branch.outputs.percentage }}
      COV_YOUR_BRANCH: ${{ needs.test-coverage-your-branch.outputs.percentage }}
      COV_MERGED_BRANCH: ${{ needs.test-coverage-merged-branch.outputs.percentage }}
    steps:
      - name: Comparison
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.BOT_PAT }}
          script: |
            // define
            let thresMainBranch = parseFloat(${{ env.THRES_MAIN_BRANCH }}); thresMainBranch = thresMainBranch ? thresMainBranch : 0;
            let thresYourBranch = parseFloat(${{ env.THRES_YOUR_BRANCH }}); thresYourBranch = thresYourBranch ? thresYourBranch : 0;
            let thresMergedBranch = parseFloat(${{ env.THRES_MERGED_BRANCH }}); thresMergedBranch = thresMergedBranch ? thresMergedBranch : 0;
            let covMainBranch = parseFloat(${{ env.COV_MAIN_BRANCH }}); covMainBranch = covMainBranch ? covMainBranch : 0;
            let covYourBranch = parseFloat(${{ env.COV_YOUR_BRANCH }}); covYourBranch = covYourBranch ? covYourBranch : 0;
            let covMergedBranch = parseFloat(${{ env.COV_MERGED_BRANCH }}); covMergedBranch = covMergedBranch ? covMergedBranch : 0;

            // diff
            let fixedDigits = 2;
            let diffYourToMain = (covYourBranch - covMainBranch).toFixed(fixedDigits);
            let diffMergedToMain = (covMergedBranch - covMainBranch).toFixed(fixedDigits);
            let diffMergedToThres = (covMergedBranch - thresMergedBranch).toFixed(fixedDigits);

            // diff color
            let diffYourToMainColor; 
            if (diffYourToMain > 0) diffYourToMainColor = "green";
            else if (diffYourToMain < 0) diffYourToMainColor = "red";
            else diffYourToMainColor = "gray";

            let diffMergedToMainColor;
            if (diffMergedToMain > 0) diffMergedToMainColor = "green";
            else if (diffMergedToMain < 0) diffMergedToMainColor = "red";
            else diffMergedToMainColor = "gray";

            // status
            let statusIcon;
            if (diffMergedToThres >= 0) statusIcon = ":white_check_mark:"
            else statusIcon = ":x:"

            // body
            let body = ` 
              ### Code Coverage ${statusIcon}

              Branch | Threshold | Coverage | Diff to \`main\`
              --- | --- | --- | --- |
              \`main\` | ${thresMainBranch}% | ${covMainBranch}% | - |
              \`your\` | ${thresYourBranch}% | ${covYourBranch}% | $\\textcolor{ ${diffYourToMainColor} }{\\text{ ${diffYourToMain}\\\\% }}$ |
              \`merged\` | ${thresMergedBranch}% | ${covMergedBranch}% | $\\textcolor{ ${diffMergedToMainColor} }{\\text{ ${diffMergedToMain}\\\\% }}$ |

              <details>
              <summary>Note</summary>

              - <b>PASS :white_check_mark: / NOT PASS :x:</b> depends on \`merged\` coverage
              - \`merged\` is merge between \`main\` and \`your\`
              - Please see directly from actions result for details of errors if any

              </details>
            `

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })
