---
# [File Changes]
#   get file changes between "main" and "pull-request" branch
name: File changes

on:
  pull_request:
    branches: main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  file-changes:
    runs-on: ubuntu-latest
    if: github.actor != 'verlandz-bot'
    steps:
      - name: Checkout pull-request branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_PAT }}

      - name: Get file changes
        id: get-file-changes
        run: |
          git fetch origin main

          diffFiles=$(git diff --name-status origin/main)
          diffFiles="${diffFiles//'%'/'<br>'}"
          diffFiles="${diffFiles//$'\n'/'<br>'}"
          diffFiles="${diffFiles//$'\r'/'<br>'}"
          echo "diff=$diffFiles" >> $GITHUB_OUTPUT

          diffStat=$(git diff --shortstat origin/main)
          echo "stat=$diffStat" >> $GITHUB_OUTPUT

      - name: Report failure
        if: failure()
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.BOT_PAT }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### :x: File Changes 
            failed to get file changes

      - name: Report result
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.BOT_PAT }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### File Changes
            ${{ steps.get-file-changes.outputs.stat }}

            <details>
            <summary>Details</summary>
            <pre>${{ steps.get-file-changes.outputs.diff }}</pre>
            </details>
