---
# [File Changes]
#   get file changes between "base" and "head" branch
name: File Changes

on:
  pull_request:
    branches:
      - main
      - beta

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  file-changes:
    runs-on: ubuntu-latest
    if: github.actor != 'verlandz-bot'
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_PAT }}

      - name: Get file changes
        id: get-file-changes
        run: |
          git fetch origin ${{ github.base_ref }}

          diffFiles=$(git diff --name-status origin/${{ github.base_ref }})
          diffFiles="${diffFiles//'%'/'<br>'}"
          diffFiles="${diffFiles//$'\n'/'<br>'}"
          diffFiles="${diffFiles//$'\r'/'<br>'}"
          echo "files=$diffFiles" >> $GITHUB_OUTPUT

          diffStats=$(git diff --shortstat origin/${{ github.base_ref }})
          echo "stats=$diffStats" >> $GITHUB_OUTPUT

      - name: Report failure
        if: failure()
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.BOT_PAT }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### :x: File Changes 
            failed to get file changes

      - name: Report result
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.BOT_PAT }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### File Changes
            ${{ steps.get-file-changes.outputs.stats }}

            <details>
            <summary>Details</summary>
            <pre>${{ steps.get-file-changes.outputs.files }}</pre>
            </details>
