---
# [Stale]
#   will put label 'stale' on issues/PRs that don't have any activity in the past N days
#   and will be automatically closed after M days.
name: Stale

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  label-or-close:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/stale@v5
        with:
          repo-token: ${{ secrets.BOT_PAT }}     
          stale-issue-message: 'This issue is stale because it has been open 14 days with no activity. Remove stale label or comment or this will be closed in 7 days'
          stale-pr-message: 'This PR is stale because it has been open 14 days with no activity. Remove stale label or comment or this will be closed in 7 days'
          stale-issue-label: 'stale'
          exempt-issue-labels: 'work-in-progress'
          stale-pr-label: 'stale'
          exempt-pr-labels: 'work-in-progress'
          days-before-stale: 14
          days-before-close: 7
